global:
  scrape_interval: 15s

scrape_configs:
  - job_name: besu-dev
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ["localhost:9545","localhost:9546"]

  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"

    # Override global settings
    scrape_interval: 5s

    static_configs:
      - targets: ["node-exporter:9100"]

  # - job_name: "tns_app"

  #   # Override global settings
  #   scrape_interval: 5s

  #   static_configs:
  #     - targets: ["app:80"]
